### PR TITLE
feat: Set Name of Series from Statement getattr

### PR DESCRIPTION
**Pull request by chrislawson-au**
This PR will add a name to the pandas series for an individual item on the income statement. For example, the Inventory series from the balance sheet.

### CODE REVIEW

**Comment by chrislawson-au** [comment]
At the moment there are no tests. Not sure of the best place to add them.

**Comment by chrislawson-au** [comment]
@nickderobertis,
Established `test_statements.py` but only added a test case for my latest feature. I can add more test coverage in the future as we develop more.
I'll need some education on the `justfile`

**Comment by nickderobertis** [comment]
Yes definitely did not intend for you to develop a full set of unit tests for statement, just the one case supporting this PR.

I'll go ahead and update the snapshots on this PR. Let's sync to get you set up with the dev environment.

**Comment by nickderobertis** [comment]
I had to update the snapshot generator to add the series names to the output. Maybe we can lean on libraries to replace this hacked setup sometime in the future. If you run something similar in another PR, for reference see 5dbd44e

**Comment by nickderobertis** [comment]
Turns out not all the integration tests are connected to the snapshot generation :sweat_smile: I guess I wrote most of the load tests before I developed that pattern. It will require a manual effort to rework these.

I really don't like the structure of these tests actually. I'm thinking I may use [syrupy](https://github.com/tophat/syrupy) and write a custom extension for serializing statements. I don't think it will take too much more time than reworking these tests into the existing pattern and we'll end up with a more modern structure.

**Comment by chrislawson-au** [comment]
let's walk through these changes together and discuss future steps.

**Pull request merged**
